application: garoahc
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: /static/favicon.ico
  upload: /static/favicon\.ico

- url: /static
  static_dir: static/

- url: /task/*
  script: main.py
  login: admin


- url: /schedule/update_image
  script: main.py
  login: admin

- url: .*
  script: main.py
